version: '3'

volumes:
  postgres:

networks:
  app-network:

services:
  bot:
    networks:
      - app-network
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - .env
  postgres:
    networks:
      - app-network
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    networks:
      - app-network
    image: adminer
    restart: unless-stopped
    env_file:
      - .env
